### ISSUE TITLE
Stuck Keys

### ISSUE THREAD

**Issue by ProbablePrime** [ProbablePrime/beam-keyboard#13]
So historically stuck keys have been caused by
- My code
- A focus bug on beam
- People actually holding down keys

Its almost impossible to tell which one of the above it is right now.

What I need is a gui window that just prints the reports coming in and live updates without scrolling angular 2 way binding/react style. This lets me see what beam is sending and isolates beam from the problem.

A second tab would then show what im sending in the same manner.

Think of it as the static view on what's going on inside the code.

**Comment by ProbablePrime** [comment]
Looks like this was caused by the crash bug, code got overwhelmed and stuck processing old reports.

**Comment by ProbablePrime** [comment]
Seeing this again

**Comment by sorryaboutyourcats** [comment]
There should be documentation on how to reload the controls remotely via bot; at least to the extent of which bot is the recommended one. :)

**Comment by ProbablePrime** [comment]
there isnt any open source bot that does this. Thus i'm not able to offer documentation on how to do it.
