### ISSUE TITLE
How do you use this with enabled 2FA?

### ISSUE THREAD

**Issue by Gol-D-Ace** [ProbablePrime/beam-keyboard#16]
Hi.

I have 2FA enabled on my account and can't use this currently apparently.
Does this support 2FA or does it need to be implemented?

Getting: `body: { message: 'Invalid two-factor code.', error: '2fa' } } }`

**Comment by 2Cubed** [comment]
Try adding `code` to your `auth.json`.

``` json
{
    "username":"<username>",
    "password":"<password>",
    "code":"<2fa-code>",
    "channel":"<channel>"
}
```

**Comment by Gol-D-Ace** [comment]
Thank you for replying.
Already tried that.
Didn't work.

**Comment by rfox90** [comment]
2fa is not supported at this time.

**Comment by Gol-D-Ace** [comment]
Thank you for letting me know. (PS: Ignore my tweet.)

**Comment by ProbablePrime** [comment]
Use Oauth, tetris:robot:self & channel:update:self are the scopes needed.
