### ISSUE TITLE
id and share code are there but it wont run

### ISSUE THREAD

**Issue by themarsman1** [ProbablePrime/beam-keyboard#20]
now its saying im missing vesrion id and share code when i clearly have them there http://prntscr.com/bxbm1b im using default.json

**Comment by kodbilenadam** [comment]
Try version between double-quote's like `version: "verno"`

**Comment by themarsman1** [comment]
nope

**Comment by ProbablePrime** [comment]
Its code, not shareCode

**Comment by ProbablePrime** [comment]
Updated the sample file, Sorry about that :)
