### ISSUE TITLE
Process is exiting wih code: 0

### ISSUE THREAD

**Issue by Avalanchewolf** [ProbablePrime/beam-keyboard#23]
Currently running into this issue, i cant find what part ive done wrong anywhere ill list the docs (Ill put ??? marks in spots that are private)
Path to files: C:\Users\???????\Desktop\interactive-keyboard-master\config

File: default.json
{
    "handler": "keyboardz",
    "version":????,
        "code":"okpg3xst"
}

File: auth.json
{
    "username":"<Avalanchewolf>",
    "token": "<tQQ??????M2I1w57imG0v????????????RmQfkCRV???????Yfo0fX4AurXr>"
}
OR
{
    "username":"<Avalanchewolf>",
    "password":"<?????????>"
}
Both end with this CMD
C:\Users\david\Desktop\interactive-keyboard-master>node index.js
using default config file
Using <Avalanchewolf> with Version: ???? && Code: okpg3xst
Process is exiting wih code: 0

Any ideas or help guys?

**Comment by rfox90** [comment]
Your auth file should contain an oauth token OR a password not both your
message seems to suggest you have both.

Try that let me know :)

**Comment by Avalanchewolf** [comment]
K, took out the "token" and lets just username password same errors happening 
C:\Users\?????\Desktop\interactive-keyboard-master>node index.js
using default config file
Using <Avalanchewolf> with Version: ???? && Code: okpg3xst
Process is exiting wih code: 0

**Comment by rfox90** [comment]
Incorrect version id or code or password ill take a look tomorrow

**Comment by Avalanchewolf** [comment]
Okay ill list out everything in more detail so you can look at it

**Comment by Avalanchewolf** [comment]
So i reinstalled it about 12times, idk what different thing i did, but its working now
