### ISSUE TITLE
Allow state changes

### ISSUE THREAD

**Issue by sorryaboutyourcats** [ProbablePrime/beam-keyboard#25]
It would be great to be able to change the state in the Lab for a specific game.
In my feature request, I will go over two scenarios:

**Game:** SNES Emulator 
**State 1:** Controls retrofitted for Super Mario World
**State 2:** Controls retrofitted for Super Bomberman

**Game:** Rocket League
**State 1:** One player controls
**State 2:** Two player controls

This would make it easier to have a consistent stream going with constantly changing ROMs.

**Comment by ProbablePrime** [comment]
You wouldn't need to change the state on the lab. 

Youplay and Merlin use different files for this. Usually when changing games we drop to a "Changing Game/setup" period whilst we get the new controls sorted.

This is the whole reason we support multiple configuration files. A file per emulator is used.

**Comment by sorryaboutyourcats** [comment]
I understand that I can load different files, like rocket.json to load my
controls for Rocket League - but what if I want to stick with the same
emulator and just change button layout to state different things.

If I load Super Mario World, the button should state Jump.
And then if I load up Secret of Mana, I want the button to state Action.

What would the best way be to approach that? I figured the whole point of
states was for that.
Instead, I have to create a bunch of new games under the Developer Lab.

Of course, if I'm misunderstanding all of this - please let me know; I am
new to all of this. =]

**Comment by ProbablePrime** [comment]
States is designed for this sort of thing yes.

States are fully supported by beam but not by this project.

I'll keep it in mind for future development

**Comment by sorryaboutyourcats** [comment]
Sounds good! And of course, thank you for your work on this!
Considering I'm now going to be sticking on Beam [because of this tool],
I'm down to test any updates you send out. =D

Thanks again!
