### ISSUE TITLE
Sectioned off controls for actual multiplayer

### ISSUE THREAD

**Issue by sorryaboutyourcats** [ProbablePrime/beam-keyboard#26]
## Feature request?

Certain set of viewers will have certain controls.
## Why?

Different people can be sectioned off to different players in the game.
This will also block them from accessing each other's controls.
[Say, Billy403 can't mess with the controls for Player 2 since he's Player 3.]
## How?

As people start the controls of the game, they'll be selected to a team.
Each team will be evenly distributed [or the viewer can select a team.]
## Games to try first?

Rocket League [4 player split]
Gang Beast [8 player same screen]
Goldeneye on N64 [emulated 4 player split]

**Comment by ProbablePrime** [comment]
This is actually somehting beam needs to support first. It falls under "Team Based Games". I'd suggest opening an idea on feedback.beam.pro about this.

**Comment by sorryaboutyourcats** [comment]
Ah didn't realize - sorry; will do.

Thanks!
