### ISSUE TITLE
OAuth setup

### ISSUE THREAD

**Issue by sorryaboutyourcats** [ProbablePrime/beam-keyboard#28]
This should be a simple task - but since I suck at this, I'm wondering if you could assist. :)

How do I load the two scopes required for OAuth authentication?
_interactive:robot:self / channel:update:self_

I figured my json file is not set properly to give the right permissions, resulting in:
_Unhandled rejection Error: Couldn't set channel to interactive with that game._

Thanks in advance & sorry to bug you. =D

**Comment by ProbablePrime** [comment]
OAuth is currently optional. Its a pretty advanced concept.

Checkout: https://dev.beam.pro/reference/oauth/index.html
I'm working on making this easier for users.

**Comment by sorryaboutyourcats** [comment]
Ah I see - I'll hold off until then. =P
Thanks for the info!
