### ISSUE TITLE
Unhandled rejection error after update

### ISSUE THREAD

**Issue by sorryaboutyourcats** [ProbablePrime/beam-keyboard#32]
After updating interactive-keyboard, I received this error when trying to establish a connection with Beam:
**Unhandled rejection Error: An unknown error occurred**

This was tested on two different computers, accounts & networks.

**Comment by ProbablePrime** [comment]
Resolved in the last two commits, update again

Thanks :)

**Comment by sorryaboutyourcats** [comment]
Works! Thanks for the update.
